packaging_format = 2

id = "couchdb"
name = "CouchDB"
description.en = "Open-source document-oriented NoSQL database"
description.fr = "Système de gestion de base de données orienté documents"

version = "3.2.2~ynh2"

maintainers = ["Squeak"]

[upstream]
license = "Apache-2.0"
website = "https://couchdb.apache.org/"
admindoc = "https://docs.couchdb.org/en/stable/"
code = "https://github.com/apache/couchdb"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/couch"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.password]
    type = "password"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.ports]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    [resources.apt]
    packages = "gnupg ca-certificates"
    extras.couchdb.repo = "deb https://apache.jfrog.io/artifactory/couchdb-deb/ bullseye main"
    extras.couchdb.key = "https://couchdb.apache.org/repo/keys.asc"
    extras.couchdb.packages = "couchdb"
