#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    [default.test_upgrade_from.0e91958cfd8406e71e9c4e506620c5e9b7110a5f]
    name = "3.1.1~ynh3"
